# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://jstools.dev/eslint-config-modular/

root: true

extends:
  - "@jsdevtools/modular/best-practices"
  - "@jsdevtools/modular/style"
  - "@jsdevtools/modular/es6"
  - "@jsdevtools/modular/node"
