- id: swagger-validation
  name: swagger-validation
  entry: swagger-cli
  description: Hook to validate swagger specs.
  language: node
  files: .*swagger.*\.(json|yaml|yml)
  args: ["validate", "swagger-ui/swagger.yml"]

