# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/migrating-from-legacy/

dist: trusty
sudo: false
language: node_js

node_js:
  - 8
  - 10
  - 12

os:
  - linux
  - osx
  - windows

script: npm run lint && npm run coverage

after_success:
  # FIXME: Travis-CI does not currently support environment variables (i.e. CODACY_PROJECT_TOKEN)
  #        on Windows. https://github.com/travis-ci/travis-build/pull/1544
  # send code-coverage data to Codacy
  #- cat ./coverage/lcov.info | node_modules/.bin/codacy-coverage -p .

  # send code-coverage data to Coveralls
  - cat ./coverage/lcov.info | coveralls
