# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

sudo: false
language: node_js
matrix:
  include:
    - node_js: 4
    - node_js: 5
    - node_js: 6
    - node_js: 7
    - node_js: 8
